name: CI-CD

on: 
  push:
    branches: ["dev"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: autentication docker hub
        uses: docker/login-action@v3.0.0
        
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Docker build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            jcs7/fundamentus:v1.0
            jcs7/fundamentus:latest
